version: '3'

services:
  nginx:
    build:
      context: ./nginx
      dockerfile: prod.Dockerfile
    image: levimartines/nginx:prod
    container_name: nginx
    networks:
      - node-network
    ports:
      - "8080:80"
    depends_on:
      - app
      - db

  app:
    container_name: app
    entrypoint: dockerize -wait tcp://db:3306 -timeout 30s docker-entrypoint.sh node index.js
    build:
      context: node
      dockerfile: Dockerfile
    networks:
      - node-network
    depends_on:
      - db

  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db
    environment:
      MYSQL_DATABASE: nodedb
      MYSQL_ROOT_PASSWORD: root
    expose:
      - 3306
    networks:
      - node-network
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

networks:
  node-network:
    driver: "bridge"
